name: reddit_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.5
  fpdart: ^1.1.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  routemaster: ^1.0.1
  sizer: ^2.0.15
  velocity_x: ^4.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/awards/
    - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/Reddit.ttf
